Hoemwork for week3 in javascript1
ehsanesmaeil/hyf-homework pull request #4
Opened 2020-08-24 06:51 UTC by ehsanesmaeil

2020-08-27 22:10 UTC, sowmya1408 requested changes
Good job!!
Use specific variable naming convention , not in general as min, hour etc...

2020-08-27 22:10 UTC, sowmya1408 commented on javascript/javascript1/week3/w3-exercise-2.js
> +  let hour = Math.trunc(distanceKm / speedKmPerH);
Variable naming conventions , hour/minute - is a general naming, be very specific.
ex: travelInHour etc...

2020-08-27 22:10 UTC, sowmya1408 commented on javascript/javascript1/week3/w3-exercise-3.js
> +let age = 80;
you can use const keyword here, as you are not reassign this variable

2020-08-31 12:28 UTC, ehsanesmaeil commented on javascript/javascript1/week3/w3-exercise-1.js
> + function deleteName(name){
Thanks for the review.

2020-09-27 10:00 UTC, merged